# api_service/Dockerfile
FROM python:3.10-slim

WORKDIR /app
COPY ../helpers ./helpers
COPY server.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
